market/urls.py
from django.urls import path

from . import views

app_name = 'market'
urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('lio/', views.lio, name='lio'),
    # market
    path('home/', views.market_home, name='market_home'),

    # developer
    path('developer_panel/', views.developer_panel_home),
    path('developer_panel/home', views.developer_panel_home, name='developer_panel_home'),
    path('developer_panel/applications', views.developer_panel_applications, name='developer_panel_applications'),
    path('developer_panel/applications/add', views.developer_panel_add_application, name='developer_panel_add_application'),
    path('developer_panel/device_catalog', views.developer_panel_device_catalog, name='developer_panel_device_catalog'),
    path('developer_panel/statistics', views.developer_panel_statistics, name='developer_panel_statistics'),
    path('developer_panel/financial', views.developer_panel_financial, name='developer_panel_financial'),
    path('developer_panel/support', views.developer_panel_support, name='developer_panel_support'),
    path('developer_panel/setting', views.developer_panel_setting, name='developer_panel_setting'),
]

market_dj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('market/', include('market.urls')),
    path('admin/', admin.site.urls),
]

market/models.py
from django.db import models
from django.core.exceptions import ValidationError


class Admin(models.Model):
    username = models.CharField(max_length=80, unique=True, blank=False)
    email = models.CharField(max_length=120, unique=True)
    passwd = models.CharField(max_length=120, blank=False)
    # passwd_salt = models.CharField(max_length=120, blank=False)

    def __str__(self):
        return self.username

class Support(models.Model):
    username = models.CharField(max_length=50, unique=True, blank=False)
    name = models.CharField(max_length=50, blank=False)
    email = models.CharField(max_length=80, unique=True, blank=False)
    role = models.CharField(max_length=30, blank=False)
    passwd = models.CharField(max_length=120, blank=False)
    # passwd_salt = models.CharField(max_length=120, blank=False)

    def clean(self):
        if not role in ('translate_service', 'developer_service', 'user_service'):
            raise ValueError('role must be translate_service, developer_service or user_service')


    def __str__(self):
        return self.username



class Developer(models.Model):
    username = models.CharField(max_length=50, blank=False, unique=True)
    name = models.CharField(max_length=50, blank=False)
    email = models.CharField(max_length=120, blank=False, unique=True)
    phone_number = models.CharField(max_length=13, blank=False, unique=True)
    passwd = models.CharField(max_length=120, blank=False)
    # paswd_salt = models.CharField(max_length=120, blank=False)
    national_id = models.CharField(max_length=10, blank=False)
    national_picture = models.CharField(max_length=120)
    zip_code = models.CharField(max_length=15)
    register_date = models.DateField(auto_now_add=True, blank=False)
    # address

    def __str__(self):
        return self.username

class Category(models.Model):
    name = models.CharField(max_length=80, blank=False, unique=True)
    category_type = models.CharField(max_length=20, blank=False, default='')

    def clean(self):
        if not self.category_type in ('app', 'game'):
            raise ValueError('role must be app or game')

    def __str__(self):
        return self.name + ' : ' + self.category_type

class Application(models.Model):
    application_name = models.CharField(max_length=80, blank=False)
    developer = models.ForeignKey(Developer, on_delete=models.CASCADE)
    application_type = models.CharField(max_length=80, blank=False)
    categories = models.ManyToManyField(Category)
    package_name = models.CharField(max_length=80, blank=False, unique=True)
    version_code = models.CharField(max_length=20, blank=False)
    app_file = models.CharField(max_length=300, blank=False)
    # Icon handled in Icon
    price = models.DecimalField(max_digits=10, decimal_places=2, blank=False, default=0)
    in_app_payment = models.BooleanField(blank=False, default=False)
    publish_status = models.CharField(max_length=20, blank=False, default='Waiting')
    # Media handled in Media
    banner = models.CharField(max_length=300)
    ad_status = models.BooleanField(blank=False, default=False)
    age_classification = models.CharField(max_length=2, blank=False, default='D')
    # Keyword handled in Keyword
    website = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    install_count = models.IntegerField(default=0)
    unistall_count = models.IntegerField(default=0)
    crash_count = models.IntegerField(default=0)
    # reviews = models.CharField(db.String(120), blank=False)
    # handled in revies
    # dont implement
    # locales = db.Column(db.String(120), blank=False)
    # analytics = db.Column(db.String(120), blank=False)

    def clean(self):
        if not self.application_type in ('app', 'game'):
            raise ValidationError('Application type must be app or game')
        if not self.publish_status in ('Published', 'Waiting', 'Removed', 'Changes Required'):
            raise ValidationError('Application publish_status must be Published, Waiting, Removed, Changes Required')
        if not self.age_classification in ('A', 'B', 'C', 'D'):
            raise ValidationError('Age classification must be A, B, C or D')


    def __str__(self):
        return self.application_name



class User(models.Model):
    username = models.CharField(max_length=50, blank=False, unique=True)
    name = models.CharField(max_length=50, blank=False)
    email = models.CharField(max_length=100, unique=True)
    phone_number = models.CharField(max_length=13, unique=True)
    passwd = models.CharField(max_length=120, blank=False)
    # passwd_salt = models.CharField(max_length=120, blank=False)
    register_date = models.DateField(auto_now_add=True, blank=False)

    #applications list
    favoriate_applications = models.ManyToManyField(Application, related_name='users_favorited')
    installed_applications = models.ManyToManyField(Application, related_name='users_installed')
    deleted_applications = models.ManyToManyField(Application, related_name='users_deleted')

    def __str__(self):
        return self.username

class Icon(models.Model):
    file_path = models.CharField(max_length=200, blank=False, unique=True)
    size = models.CharField(max_length=5, blank=False)
    application = models.ForeignKey(Application, on_delete=models.CASCADE)

    def clean(self):
        if not self.size in ('16', '24', '32', '48'):
            ValueError('Icon size must be 16, 24, 32, or 48 ')


class Media(models.Model):
    media_type = models.CharField(max_length=10, blank=False)
    file_path = models.CharField(max_length=200, blank=False)
    application = models.ForeignKey(Application, on_delete=models.CASCADE)

    def clean(self):
        if not self.media_type in ('picture', 'video'):
            raise ValueError('media type must be picture or video')


class Keyword(models.Model):
    name = models.CharField(max_length=80, blank=False, unique=True)
    application = models.ForeignKey(Application, on_delete=models.CASCADE)


class Review(models.Model):
    text = models.CharField(max_length=600, blank=False)
    rate = models.IntegerField(blank=False)
    # review_status = db.Column(db.String(30), blank=False, CheckConstraint(review_status in ('confirmed', 'removed', 'waiting')))
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    application = models.ForeignKey(Application, on_delete=models.CASCADE)

    def clean(self):
        if not self.rate in (1, 2, 3, 4, 5):
            raise ValueError('rate must be 1, 2, 3, 4 or 5')


    def __str__(self):
        return self.text[:20]

# payments
class UserPayment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    Application = models.ForeignKey(Application, on_delete=models.CASCADE)
    value = models.DecimalField(max_digits=10, decimal_places=2, blank=False)
    payment_type = models.CharField(max_length=30, blank=False)
    date = models.DateField(auto_now_add=True, blank=False)

    def clean(self):
        if not payment_type in ('inapp', 'buy'):
            raise ValidationError('payment_type must be inapp or buy')


class DeveloperInPayment(models.Model):
    developer = models.ForeignKey(Developer, on_delete=models.CASCADE)
    Application = models.ForeignKey(Application, on_delete=models.CASCADE)
    value = models.DecimalField(max_digits=10, decimal_places=2, blank=False)
    payment_type = models.CharField(max_length=30, blank=False)
    date = models.DateField(auto_now_add=True, blank=False)

    def clean(self):
        if not payment_type in ('inapp', 'buy', 'market', 'advertise', 'gift'):
            raise ValidationError('payment_type must be inapp, buy, market, advertise or gift')


class DeveloperOutPayment(models.Model):
    developer = models.ForeignKey(Developer, on_delete=models.CASCADE)
    Application = models.ForeignKey(Application, on_delete=models.CASCADE)
    value = models.DecimalField(max_digits=10, decimal_places=2, blank=False)
    payment_type = models.CharField(max_length=30, blank=False)
    date = models.DateField(auto_now_add=True, blank=False)

    def clean(self):
        if not payment_type in ('register', 'translation', 'advertise', 'cross-promotion'):
            raise ValidationError('payment_type must be register, translation, advertise, cross-promotion')

market/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.views.generic import View
from .models import User


def index(request):
    return HttpResponse("Hello, world. You're at the polls index.")


def lio(request):
    return render(request, 'market/lio.html')

class SignUp(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'market/signup.html')

    def post(self, request, *args, **kwargs):
        username = request.post['username']
        email = request.post['email']
        passwd = request.post['passwd']
        phone_number = request.post['phone_number']
        pass


# market
def market_home(request):
    recoms = [
        {'name': 'DATA WING', 'img': '03.png', 'cost': 'FREE'},
        {'name': 'iTaxi', 'img': '05.png', 'cost': 'FREE'},
        {'name': 'Home Workout', 'img': '04.png', 'cost': '2.9$'},
        {'name': 'Lingua Player', 'img': '02.png', 'cost': 'FREE'},
    ]

    tops = [
        {'name': 'Swipe Brick', 'img': '06.png', 'cost': 'FREE'},
        {'name': 'Shadow Fight 3', 'img': '07.png', 'cost': 'FREE'},
        {'name': 'Chilly Snow', 'img': '08.png', 'cost': '2.9$'},
        {'name': 'Rubik\'s Cube', 'img': '09.png', 'cost': 'FREE'},
    ]

    tus = [
        {'name': 'VPN Free', 'img': '10.png', 'cost': 'FREE'},
        {'name': 'VPN Monster', 'img': '11.png', 'cost': 'FREE'},
        {'name': 'Lantern', 'img': '12.png', 'cost': '2.9$'},
        {'name': 'Hi VPN', 'img': '13.png', 'cost': 'FREE'},
    ]

    return render(request, 'market/market_home.html', {'recoms': recoms, 'tops': tops, 'tus': tus})

# developer
def developer_panel_home(request):
    return render(request, 'market/dp_home.html', {'home': 1})

def developer_panel_applications(request):
    apps = [
        {'name': 'app1', 'type': 'type1', 'category': 'cat1', 'status': 'published', 'downloads': '1234'},
        {'name': 'app2', 'type': 'type2', 'category': 'cat2', 'status': 'changes required', 'downloads': '2345'},
        {'name': 'app3', 'type': 'type3', 'category': 'cat3', 'status': 'waitting', 'downloads': '3456'}
    ]
    return render(request, 'market/dp_applications.html', {'applications': 1, 'apps': apps})


def developer_panel_add_application(request):
    apps = [
        {'name': 'app1', 'type': 'type1', 'category': 'cat1', 'status': 'published', 'downloads': '1234'},
        {'name': 'app2', 'type': 'type2', 'category': 'cat2', 'status': 'changes required', 'downloads': '2345'},
        {'name': 'app3', 'type': 'type3', 'category': 'cat3', 'status': 'waitting', 'downloads': '3456'}
    ]
    return render(request, 'market/dp_add_application.html', {'applications': 1, 'apps': apps})

def developer_panel_device_catalog(request):
    return render(request, 'market/dp_device_catalog.html', {'device_catalog': 1})

def developer_panel_statistics(request):
    return render(request, 'market/dp_statistics.html', {'statistics': 1})

def developer_panel_financial(request):
    return render(request, 'market/dp_financial.html', {'financial': 1})

def developer_panel_support(request):
    return render(request, 'market/dp_support.html', {'support': 1})

def developer_panel_setting(request):
    return render(request, 'market/dp_setting.html', {'setting': 1})

market/templates/market/dp.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css">
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
{% block header_end %}
{% endblock %}
{% load static %}
<link rel="stylesheet" href="{% static 'market/developer_panel.css' %}">
<body class="home">
    <div class="container-fluid display-table">
        <div class="row display-table-row">
            <div class="col-md-2 col-sm-1 hidden-xs display-table-cell v-align box" id="navigation">
                <div class="logo">
                    <!-- Mamad Market -->
                    <a hef="home.html"><img src="http://jskrishna.com/work/merkury/images/logo.png" alt="merkery_logo" class="hidden-xs hidden-sm">
                        <img src="http://jskrishna.com/work/merkury/images/circle-logo.png" alt="merkery_logo" class="visible-xs visible-sm circle-logo">
                    </a>
                </div>
                <div class="navi">
                    <ul>
                        <li class='{% if home %} active{% endif %}'><a href="{% url 'market:developer_panel_home' %}"><i class="fa fa-home" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Home</span></a></li>
                        <li class='{% if applications %} active{% endif %}'><a href="{% url 'market:developer_panel_applications' %}"><i class="fa fa-android" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Applications</span></a></li>
                        <li class='{% if device_catalog %} active{% endif %}'><a href="{% url 'market:developer_panel_device_catalog' %}"><i class="fa fa-laptop" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Device Catalog</span></a></li>
                        <li class='{% if statistics %} active{% endif %}'><a href="{% url 'market:developer_panel_statistics' %}"><i class="fa fa-bar-chart" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Statistics</span></a></li>
                        <li class='{% if financial %} active{% endif %}'><a href="{% url 'market:developer_panel_financial' %}"><i class="fa fa-credit-card" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Financial</span></a></li>
                        <li class='{% if support %} active{% endif %}'><a href="{% url 'market:developer_panel_support' %}"><i class="fa fa-ambulance" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Support</span></a></li>
                        <li class='{% if setting %} active{% endif %}'><a href="{% url 'market:developer_panel_setting' %}"><i class="fa fa-cog" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Setting</span></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-10 col-sm-11 display-table-cell v-align">
                <!--<button type="button" class="slide-toggle">Slide Toggle</button> -->
                <div class="row">
                    <header>
                        <div class="col-md-7">
                            <nav class="navbar-default pull-left">
                                <div class="navbar-header">
                                    <button type="button" class="navbar-toggle collapsed" data-toggle="offcanvas" data-target="#side-menu" aria-expanded="false">
                                        <span class="sr-only">Toggle navigation</span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                    </button>
                                </div>
                            </nav>
                            <div class="search hidden-xs hidden-sm">
                                <input type="text" placeholder="Search" id="search">
                            </div>
                        </div>
                        <div class="col-md-5">
                            <div class="header-rightside">
                                <ul class="list-inline header-top pull-right">
                                    <li class="hidden-xs"><a href="{% url 'market:developer_panel_add_application' %}" class="add-project" data-toggle="modal" data-target="#add_project">Add Application</a></li>
                                    <li><a href="#"><i class="fa fa-envelope" aria-hidden="true"></i></a></li>
                                    <li>
                                        <a href="#" class="icon-info">
                                            <i class="fa fa-bell" aria-hidden="true"></i>
                                            <span class="label label-primary">3</span>
                                        </a>
                                    </li>
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><img src="http://jskrishna.com/work/merkury/images/user-pic.jpg" alt="user">
                                            <b class="caret"></b></a>
                                        <ul class="dropdown-menu">
                                            <li>
                                                <div class="navbar-content">
                                                    <span>JS Krishna</span>
                                                    <p class="text-muted small">
                                                        me@jskrishna.com
                                                    </p>
                                                    <div class="divider">
                                                    </div>
                                                    <a href="#" class="view btn-sm active">View Profile</a>
                                                </div>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </header>
                </div>
                <div class="user-dashboard">
                    {% block content %}
                    {% endblock %}
            </div>
        </div>

    </div>



    <!-- Modal -->
    <div id="add_project" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header login-header">
                    <button type="button" class="close" data-dismiss="modal">×</button>
                    <h4 class="modal-title">Add Project</h4>
                </div>
                <div class="modal-body">
                            <input type="text" placeholder="Project Title" name="name">
                            <input type="text" placeholder="Post of Post" name="mail">
                            <input type="text" placeholder="Author" name="passsword">
                            <textarea placeholder="Desicrption"></textarea>
                    </div>
                <div class="modal-footer">
                    <button type="button" class="cancel" data-dismiss="modal">Close</button>
                    <button type="button" class="add-project" data-dismiss="modal">Save</button>
                </div>
            </div>

        </div>
    </div>


    <script>
        $(document).ready(function(){
            $('[data-toggle="offcanvas"]').click(function(){
                $("#navigation").toggleClass("hidden-xs");
            });
        });
    </script>
    {% block end_body %}
    {% endblock %}
</body>

market/templates/market/dp_applications.html
{% extends "market/dp.html" %}

{% block content %}
<h1>Applications</h1>
<div class="row">
    <!-- <div class="col-md-5 col-sm-5 col-xs-12 gutter"> -->


        <div class="sales">
            <div>
                <table class='table'>
                    <tr>
                        <th>Application Name</th>
                        <th>Type</th>
                        <th>Category</th>
                        <th>Staus</th>
                        <th>Downloads</th>
                        <th></th>
                        <th></th>
                    </tr>
                    {% for application in apps %}
                        <tr>
                            <td>{{ application.name }}</td>
                            <td>{{ application.type }}</td>
                            <td>{{ application.category }}</td>
                            <td>{{ application.status }}</td>
                            <td>{{ application.downloads }}</td>
                            <td><i class="fa fa-pencil" aria-hidden="true"></i></td>
                            <td><i class="fa fa-trash-o" aria-hidden="true"></i></td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
</div>
{% endblock %}

market/templates/market/dp_device_catalog.html
{% extends "market/dp.html" %}

{% block content %}
<h1>Device Catalog</h1>
<div class="row">
    <div class="col-md-5 col-sm-5 col-xs-12 gutter">

        <div class="sales">
            <h2>Your Sale</h2>

            <div class="btn-group">
                <button class="btn btn-secondary btn-lg dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span>Period:</span> Last Year
                </button>
                <div class="dropdown-menu">
                    <a href="#">2012</a>
                    <a href="#">2014</a>
                    <a href="#">2015</a>
                    <a href="#">2016</a>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-7 col-sm-7 col-xs-12 gutter">

        <div class="sales report">
            <h2>Report</h2>
            <div class="btn-group">
                <button class="btn btn-secondary btn-lg dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span>Period:</span> Last Year
                </button>
                <div class="dropdown-menu">
                    <a href="#">2012</a>
                    <a href="#">2014</a>
                    <a href="#">2015</a>
                    <a href="#">2016</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

market/templates/market/dp_support.html
{% extends "market/dp.html" %}

{% block content %}
<h1>Support</h1>
<div class="row">

        <div class="sales">
            <form>
                <div class="form-group">
                    <label for="ticket_title">Ticket title</label>
                    <input type="text" class="form-control" id="ticket_title" placeholder="Title">
                </div>
                <div class="form-group">
                    <label for="message">Message</label>
                    <!-- <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password"> -->
                    <textarea class="form-control" rows="3" id="message" placeholder="Message"></textarea>
                </div>
                <button type="submit" class="btn btn-default">Send</button>
            </form>
        </div>

</div>
{% endblock %}

market/templates/market/market_home.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Mamad Market</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
    {% load static %}
	<link rel="stylesheet" href="{% static 'market/heroic-features.css' %}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Mamad Market</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url 'market:lio' %}">Login</a>
                    </li>
                    <li>
                        <a href="{% url 'market:developer_panel_home' %}">Developer</a>
                    </li>
                    <li>
                        <a href="#">Services</a>
                    </li>
                    <li>
                        <a href="#">Contact</a>
                    </li>
                    <li>
                        <a href="#">About</a>
                    </li>
                </ul>
                <form class="navbar-form navbar-right" method='get' action='search'>
                  <input type="text" class="form-control" placeholder="Search Mamad Market...">
                </form>
            </div>

            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>


    <!-- Page Content -->
    <div class="container">

        <!-- Jumbotron Header -->
        <header class="jumbotron hero-spacer">
            <h1>A Warm Welcome!</h1>
            <p><a class="btn btn-primary btn-large" href={% url 'market:lio' %}>Join Mamad Market Now</a>
            </p>
        </header>

        <hr>

        <div class="row">
            <div class="col-lg-12">
                <h3>Recommended for you</h3>
            </div>
        </div>

        <div class="row text-center">
            {% for rec in recoms %}
                <div class="col-md-3 col-sm-6 hero-feature">
                    <div class="thumbnail">
                        <img src="{% static 'market/app-img' %}/{{ rec.img }}" alt="{{ rec.name }}">
                        <div class="caption">
                            <h3>{{ rec.name }}</h3>
                            <p>
                                <a href="#" class="btn btn-primary">GET</a> <a href="#" class="btn btn-default">{{ rec.cost }}</a>
                            </p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

        <hr>

        <div class="row">
            <div class="col-lg-12">
                <h3>Top Rated</h3>
            </div>
        </div>

        <div class="row text-center">
            {% for rec in tops %}
                <div class="col-md-3 col-sm-6 hero-feature">
                    <div class="thumbnail">
                        <img src="{% static 'market/app-img' %}/{{ rec.img }}" alt="{{ rec.name }}">
                        <div class="caption">
                            <h3>{{ rec.name }}</h3>
                            <p>
                                <a href="#" class="btn btn-primary">GET</a> <a href="#" class="btn btn-default">{{ rec.cost }}</a>
                            </p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>


        <hr>

        <div class="row">
            <div class="col-lg-12">
                <h3>Ghand Shekan</h3>
            </div>
        </div>

        <div class="row text-center">
            {% for rec in tus %}
                <div class="col-md-3 col-sm-6 hero-feature">
                    <div class="thumbnail">
                        <img src="{% static 'market/app-img' %}/{{ rec.img }}" alt="{{ rec.name }}">
                        <div class="caption">
                            <h3>{{ rec.name }}</h3>
                            <p>
                                <a href="#" class="btn btn-primary">GET</a> <a href="#" class="btn btn-default">{{ rec.cost }}</a>
                            </p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Mamad Market 2018</p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->


    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>

</html>

market/templates/market/signup.html
<form action="{% url 'market:signup' %}" method="post">
    <input type="text" name="username" placeholder="username">
    <input type="text" name="email" placeholder="email">
    <input type="text" name="passwd" placeholder="password">
    <input type="text" name="phone_number" placeholder="phone number">
</form>